# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkext < Formula
  desc "Modern Go-based tool for extracting and building APK files with embedded JAR utilities"
  homepage "https://github.com/dmikushin/apkext"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmikushin/apkext/releases/download/v1.0.0/apkext_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "a8cc6c24548772a43babb22a35ce760473032acdae670abbd03969df70bc16c9"

      def install
        bin.install "apkext"
      end
    end
    on_arm do
      url "https://github.com/dmikushin/apkext/releases/download/v1.0.0/apkext_1.0.0_Darwin_arm64.tar.gz"
      sha256 "d68d624693e210a39c70e1258143e0477d2f9f08f8bed4b53a8acd9c6d31c96f"

      def install
        bin.install "apkext"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/apkext/releases/download/v1.0.0/apkext_1.0.0_Linux_x86_64.tar.gz"
        sha256 "552d32dd48ddd56417cb3c6f66e20d82402d2e2314e0168e7350b6e26aa60c57"

        def install
          bin.install "apkext"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/apkext/releases/download/v1.0.0/apkext_1.0.0_Linux_arm64.tar.gz"
        sha256 "d2ac3a3b0be09c1e6672e34c30519ea683ef2520e828a2513e8282a1ae47afe6"

        def install
          bin.install "apkext"
        end
      end
    end
  end

  test do
    system "#{bin}/apkext", "--version"
  end
end
