# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkext < Formula
  desc "Modern Go-based tool for extracting and building APK files with embedded JAR utilities"
  homepage "https://github.com/dmikushin/apkext"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmikushin/apkext/releases/download/v1.0.1/apkext_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "2c057e71a1fc168899e1953c5e943138da718f6779e6ad9c31a95f4cdc3bf7d7"

      def install
        bin.install "apkext"
      end
    end
    on_arm do
      url "https://github.com/dmikushin/apkext/releases/download/v1.0.1/apkext_1.0.1_Darwin_arm64.tar.gz"
      sha256 "750f269fc3de0d0f9e3df01673e09b742097abf1860a3e7cf044e95ae0e64983"

      def install
        bin.install "apkext"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/apkext/releases/download/v1.0.1/apkext_1.0.1_Linux_x86_64.tar.gz"
        sha256 "62765862d026611d0b467d2850a975662ef2a95afaeeb92d90a4b225408f345e"

        def install
          bin.install "apkext"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/apkext/releases/download/v1.0.1/apkext_1.0.1_Linux_arm64.tar.gz"
        sha256 "a9ed7d2e79e22b55e84bc8167905362617b955374622317288e299f0afdf9c5e"

        def install
          bin.install "apkext"
        end
      end
    end
  end

  test do
    system "#{bin}/apkext", "--version"
  end
end
