# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkext < Formula
  desc "Modern Go-based tool for extracting and building APK files with embedded JAR utilities"
  homepage "https://github.com/dmikushin/apkext"
  version "1.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmikushin/apkext/releases/download/v1.0.2/apkext_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "c21ac1d3305cca4385a64c5ebca5369d4e8bad540932a0a52a56d4c576d16271"

      def install
        bin.install "apkext"
      end
    end
    on_arm do
      url "https://github.com/dmikushin/apkext/releases/download/v1.0.2/apkext_1.0.2_Darwin_arm64.tar.gz"
      sha256 "c5e914bfa9e38e751924961d1338bb13a2410854aa469ed446b27353f1a62d51"

      def install
        bin.install "apkext"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/apkext/releases/download/v1.0.2/apkext_1.0.2_Linux_x86_64.tar.gz"
        sha256 "4c2012d293987132679509100139b956ec4996ea8d543928f8288c2ed7183f7f"

        def install
          bin.install "apkext"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/apkext/releases/download/v1.0.2/apkext_1.0.2_Linux_arm64.tar.gz"
        sha256 "d292befe2505f8596bfbd5b22e6a57fe09aefee01541445b2e7f48ac83e0c8f5"

        def install
          bin.install "apkext"
        end
      end
    end
  end

  test do
    system "#{bin}/apkext", "--version"
  end
end
