# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Namealive < Formula
  desc "High-performance network host discovery and identification tool"
  homepage "https://github.com/dmikushin/namealive"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmikushin/namealive/releases/download/v1.0.0/namealive_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "0fc26dfd540cb65ed031590bc828371fc687c03d3cd7f5844a409e30fdbf0a7a"

      def install
        bin.install "namealive"
      end
    end
    on_arm do
      url "https://github.com/dmikushin/namealive/releases/download/v1.0.0/namealive_1.0.0_Darwin_arm64.tar.gz"
      sha256 "0f3639fb4669882a56698565a7c324cbffb60cace5d84903e369dcc1b04ce2ff"

      def install
        bin.install "namealive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.0.0/namealive_1.0.0_Linux_x86_64.tar.gz"
        sha256 "807eb7862197ac56fca1200ffc187913b67fc59a6e4d7327d885fed9ae634f14"

        def install
          bin.install "namealive"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.0.0/namealive_1.0.0_Linux_armv6.tar.gz"
        sha256 "db2f0031d850728814e018e1363e3c8b6847ed2a204e791a92cc06e217a603e1"

        def install
          bin.install "namealive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.0.0/namealive_1.0.0_Linux_arm64.tar.gz"
        sha256 "19dd87d5d43d927c60ea18d83f99feb5ee20f743289d26d8d0121e08db6d0a25"

        def install
          bin.install "namealive"
        end
      end
    end
  end

  test do
    system "#{bin}/namealive", "--version"
  end
end
