# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Namealive < Formula
  desc "High-performance network host discovery and identification tool"
  homepage "https://github.com/dmikushin/namealive"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmikushin/namealive/releases/download/v1.2.0/namealive_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "c38dc43a71bb784e4ca26a216c2f5e5591275d255600d683a72806b84b4223f8"

      def install
        bin.install "namealive"
      end
    end
    on_arm do
      url "https://github.com/dmikushin/namealive/releases/download/v1.2.0/namealive_1.2.0_Darwin_arm64.tar.gz"
      sha256 "cb7c02dc76f27e917a41848cb40740198b54721b182684e23c2d060f4a6fc7c4"

      def install
        bin.install "namealive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.2.0/namealive_1.2.0_Linux_x86_64.tar.gz"
        sha256 "7f04aade5c48c6e697252b49908ace8c187d745c1a1785d5e59efaee20265eda"

        def install
          bin.install "namealive"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.2.0/namealive_1.2.0_Linux_armv6.tar.gz"
        sha256 "34aed6e3e147054d4a9e35bdded4dd07aa27ece7bd054d9d2395ea5fbc9f4dc5"

        def install
          bin.install "namealive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.2.0/namealive_1.2.0_Linux_arm64.tar.gz"
        sha256 "af6a121e86ac68829a4082366ed9d8c8cd72c525c35ecb254853dcdb049d1a7d"

        def install
          bin.install "namealive"
        end
      end
    end
  end

  test do
    system "#{bin}/namealive", "--version"
  end
end
