# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Namealive < Formula
  desc "High-performance network host discovery and identification tool"
  homepage "https://github.com/dmikushin/namealive"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dmikushin/namealive/releases/download/v1.1.0/namealive_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "d11b1873d10d03c46f25dc76b3487d8a6f67fdb50835188d3793597c14643ff4"

      def install
        bin.install "namealive"
      end
    end
    on_arm do
      url "https://github.com/dmikushin/namealive/releases/download/v1.1.0/namealive_1.1.0_Darwin_arm64.tar.gz"
      sha256 "31c3f8a84d74d997ec4a16bb3d188d22628d6e2abff1843fb8d3f27095999fb1"

      def install
        bin.install "namealive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.1.0/namealive_1.1.0_Linux_x86_64.tar.gz"
        sha256 "f140d48a944e7c98ba74a55e0572698e46589c9a61271ec6176ebb75ea4e2d30"

        def install
          bin.install "namealive"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.1.0/namealive_1.1.0_Linux_armv6.tar.gz"
        sha256 "42ee643643e3079e06f940b14a448e61dc16aadf564badcbdfbf9ecdc273ec78"

        def install
          bin.install "namealive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dmikushin/namealive/releases/download/v1.1.0/namealive_1.1.0_Linux_arm64.tar.gz"
        sha256 "49c45b4c423c67b9e3fe217ee61bd379071b7e758c7ff1c3dbeda28f738ff9ec"

        def install
          bin.install "namealive"
        end
      end
    end
  end

  test do
    system "#{bin}/namealive", "--version"
  end
end
